language: python
python: "3.4"
env:
  matrix:
  - TOXENV=pypy3
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=pylint
install: pip install tox coveralls
script: tox -v
after_success:
  - coveralls
